name: MinecraftCalculator
main: MinecraftCalculator.Main
version: 0.0
author: yabobay
commands:
  calc:
    description: Do some math!
    usage: /calc [some math using */+- and parentheses if you want]
    permittion: MinecraftCalculator.basic
    permission-message: You don't have permission to run /calc
